{"cells":[{"cell_type":"markdown","metadata":{"id":"BTTKizbri2zC"},"source":["The **first code block** imports all the necessary packages. \n","The **second code block** mounts google drive so that this script can read files located there.\n","The **third code block** ensures that we are reading from the correct directory.\n"]},{"cell_type":"code","execution_count":1,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":23079,"status":"ok","timestamp":1681429441671,"user":{"displayName":"Genius Zoo","userId":"07986300994128194370"},"user_tz":300},"id":"vjHsHBnKc-fw","outputId":"6fc6ec25-99de-42d2-cfd7-1fe86e4b2590"},"outputs":[{"output_type":"stream","name":"stdout","text":["Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/\n","Collecting text2emotion\n","  Downloading text2emotion-0.0.5-py3-none-any.whl (57 kB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m57.8/57.8 kB\u001b[0m \u001b[31m658.4 kB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hCollecting emoji>=0.6.0\n","  Downloading emoji-2.2.0.tar.gz (240 kB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m240.9/240.9 kB\u001b[0m \u001b[31m15.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n","Requirement already satisfied: nltk in /usr/local/lib/python3.9/dist-packages (from text2emotion) (3.8.1)\n","Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.9/dist-packages (from nltk->text2emotion) (2022.10.31)\n","Requirement already satisfied: tqdm in /usr/local/lib/python3.9/dist-packages (from nltk->text2emotion) (4.65.0)\n","Requirement already satisfied: joblib in /usr/local/lib/python3.9/dist-packages (from nltk->text2emotion) (1.2.0)\n","Requirement already satisfied: click in /usr/local/lib/python3.9/dist-packages (from nltk->text2emotion) (8.1.3)\n","Building wheels for collected packages: emoji\n","  Building wheel for emoji (setup.py) ... \u001b[?25l\u001b[?25hdone\n","  Created wheel for emoji: filename=emoji-2.2.0-py3-none-any.whl size=234926 sha256=b50434c07a44c51b9a79e74cb247cfb796f424058a1d3c03f40b0c41e6c1bd43\n","  Stored in directory: /root/.cache/pip/wheels/9a/b8/0f/f580817231cbf59f6ade9fd132ff60ada1de9f7dc85521f857\n","Successfully built emoji\n","Installing collected packages: emoji, text2emotion\n","Successfully installed emoji-2.2.0 text2emotion-0.0.5\n","Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/\n","Collecting emoji==1.7\n","  Downloading emoji-1.7.0.tar.gz (175 kB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m175.4/175.4 kB\u001b[0m \u001b[31m3.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n","Building wheels for collected packages: emoji\n","  Building wheel for emoji (setup.py) ... \u001b[?25l\u001b[?25hdone\n","  Created wheel for emoji: filename=emoji-1.7.0-py3-none-any.whl size=171048 sha256=4ed85417b61313180b34ebf14bbc4d4277fb5ea8b3a6f46af8a015c4267baae1\n","  Stored in directory: /root/.cache/pip/wheels/fa/7a/e9/22dd0515e1bad255e51663ee513a2fa839c95934c5fc301090\n","Successfully built emoji\n","Installing collected packages: emoji\n","  Attempting uninstall: emoji\n","    Found existing installation: emoji 2.2.0\n","    Uninstalling emoji-2.2.0:\n","      Successfully uninstalled emoji-2.2.0\n","Successfully installed emoji-1.7.0\n"]},{"output_type":"stream","name":"stderr","text":["[nltk_data] Downloading package stopwords to /root/nltk_data...\n","[nltk_data]   Unzipping corpora/stopwords.zip.\n","[nltk_data] Downloading package punkt to /root/nltk_data...\n","[nltk_data]   Unzipping tokenizers/punkt.zip.\n","[nltk_data] Downloading package wordnet to /root/nltk_data...\n"]}],"source":["from bs4 import BeautifulSoup\n","import os\n","import re\n","!pip install text2emotion\n","!pip install emoji==1.7\n","import text2emotion as te\n","import json"]},{"cell_type":"code","execution_count":2,"metadata":{"executionInfo":{"elapsed":417,"status":"ok","timestamp":1681429442078,"user":{"displayName":"Genius Zoo","userId":"07986300994128194370"},"user_tz":300},"id":"JxwsoUuOHDEi"},"outputs":[],"source":["import pandas as pd"]},{"cell_type":"code","execution_count":3,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":26534,"status":"ok","timestamp":1681429468600,"user":{"displayName":"Genius Zoo","userId":"07986300994128194370"},"user_tz":300},"id":"oy2iRMkC5UDU","outputId":"ee61aa4c-f844-4c54-b1a8-c04194f23004"},"outputs":[{"output_type":"stream","name":"stdout","text":["Mounted at /content/drive\n"]}],"source":["from google.colab import drive\n","drive.mount('/content/drive')"]},{"cell_type":"code","execution_count":4,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":198},"executionInfo":{"elapsed":16,"status":"error","timestamp":1681429468600,"user":{"displayName":"Genius Zoo","userId":"07986300994128194370"},"user_tz":300},"id":"n3aIzpmj8e3R","outputId":"bad40094-69cf-44f8-a57e-3eff15661182"},"outputs":[{"output_type":"error","ename":"FileNotFoundError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mFileNotFoundError\u001b[0m                         Traceback (most recent call last)","\u001b[0;32m<ipython-input-4-95e39204ef64>\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mos\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mchdir\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'/content/drive/MyDrive/NewMN_dwnlds/NewMN_dwnlds'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0mdirectory\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mos\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mgetcwd\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mlen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mos\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlistdir\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mFileNotFoundError\u001b[0m: [Errno 2] No such file or directory: '/content/drive/MyDrive/NewMN_dwnlds/NewMN_dwnlds'"]}],"source":["os.chdir('/content/drive/MyDrive/NewMN_dwnlds/NewMN_dwnlds')\n","directory = os.getcwd()\n","print(len(os.listdir()))"]},{"cell_type":"markdown","metadata":{"id":"hlwGFOJK082s"},"source":["The **following code block** is used to explore the text. It is determined that **discussion items is an h2 tag**. p tags within the discussion items h2 tag \n","contain the text that we want to extract."]},{"cell_type":"code","execution_count":null,"metadata":{"id":"hEPUzghCdQgr"},"outputs":[],"source":["with open('Meeting Notes 2008 05 20 - Noisebridge.mht') as file:\n","  soup = BeautifulSoup(file.read(), 'html.parser')\n","counter = 0\n","# find all li & h2 elements elements in the HTML\n","find_list_items = soup.find_all('li')\n","find_h2_tags = soup.find_all('h2')\n","find_p_elements = soup.find_all('p')\n","\n","discussion_items_text = []\n","\n","for h2 in soup.find_all('h2'):\n","  if 'Meeting Notes' in h2.text:\n","    for p in b.find_all_next('p'):\n","      discussion_items_text.append(p.text)\n","      print(p.text)\n","      print('WHAT ARE YOU SAYING')\n","      for li in h2.find_all_next('li'):\n","        discussion_items_text.append(li.text)\n","\n","print(discussion_items_text)"]},{"cell_type":"markdown","metadata":{"id":"QQTspwwtPaXc"},"source":["In the following code block we are iterating through all the meeting notes one by one, saving the document name and extracting the discussion text. The html header for the discussion text varies quite a bit from document to document, so we have included a series of if statements that seek to capture the discussion text regardless of the header type. There are however, a number of documents for which the meeting notes have not been captured. A preliminary QA shows that most of these notes have very little information. "]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":26499,"status":"ok","timestamp":1681222249906,"user":{"displayName":"Tim Poll","userId":"04586018797185094655"},"user_tz":300},"id":"jKWfkmuXyEoz","outputId":"6db429a6-dcc5-415c-e401-634357346782"},"outputs":[{"name":"stdout","output_type":"stream","text":["Meeting_Notes_2020_02_25\n","Meeting_Notes_2019_11_26\n","Meeting_Notes_2017_05_09\n","Meeting_Notes_2017_05_16\n","Meeting_Notes_2009_08_04\n","Meeting_Notes_2009_03_31\n","Meeting_Notes_2008_09_30\n","Meeting_Notes_2009_03_24\n","Meeting_Notes_2009_02_03\n","Meeting_Notes_2009_01_27\n","Meeting_Notes_2009_01_20\n","Meeting_Notes_2008_11_25\n","Meeting_Notes_2009_02_24\n","Meeting_Notes_2009_02_17\n","Meeting_Notes_2009_03_10\n","Meeting_Notes_2008_12_09\n","Meeting_Notes_2008_12_02\n","Meeting_Notes_2009_04_07\n","Meeting_Notes_2009_02_10\n","Meeting_Notes_2008_07_01\n","Meeting_Notes_2008_02_26\n","Meeting_Notes_2007_12_04\n","Meeting_Notes_2008_01_15\n","Meeting_Notes_2008_05_27\n","Meeting_Notes_2013_06_11\n","Meeting_Notes_2012_05_22\n","Meeting_Notes_2012_03_13\n","Meeting_Notes_2011_02_08\n","Meeting_Notes_2010_12_14\n","Meeting_Notes_2011_01_25\n","Meeting_Notes_2011_01_18\n","Meeting_Notes_2010_01_05\n","Meeting_Notes_2009_12_01\n","Meeting_Notes_2010_11_02\n","Meeting_Notes_2009_03_17\n","35\n"]}],"source":["document_name = [] \n","text_list = []\n","\n","for file in os.listdir(directory):\n","    with open(file, 'r') as fileHandle:\n","      mht_doc = fileHandle.read()\n","      soup = BeautifulSoup(mht_doc, 'html.parser')\n","      document_name.append((os.path.splitext(file)[0]))\n","      text = []\n","      for h1 in soup.find_all('h1'):\n","        if 'Discussion Items' in h1.text or 'Discussion Notes' in h1.text or 'Discussion' in h1.text or 'Excellence' in h1.text:\n","          for p in h1.find_all_next('p'):\n","              text.append(p.text)\n","          for li in h1.find_all_next('li'):\n","            text.append(li.text)\n","          for ul in h1.find_all_next('ul'):\n","            text.append(ul.text)\n","        elif '2014' in h1.text or '2015' in h1.text or'2016' in h1.text or'2017' in h1.text or'2018' in h1.text or'2019' in h1.text or'2020' in h1.text:\n","          for p in h1.find_all_next('p'):\n","            text.append(p.text)\n","      for h2 in soup.find_all('h2'):\n","        if 'Meeting Notes' in h2.text or 'Discussion' in h2.text or 'Notes' in h2.text or 'Excellence' in h2.text:\n","          for p in h2.find_all_next('p'):\n","              text.append(p.text)\n","          for li in h2.find_all_next('li'):\n","            text.append(li.text)\n","        elif 'Discussion Items' in h2.text:\n","          for p in h2.find_all_next('p'):\n","              text.append(p.text)\n","          for li in h2.find_all_next('li'):\n","            text.append(li.text)\n","      for h3 in soup.find_all('h3'):\n","        if 'Discussion Items' in h3.text:\n","          for p in h3.find_all_next('p'):\n","              text.append(p.text)\n","          for li in h3.find_all_next('li'):\n","            text.append(li.text)\n","        for b in soup.find_all('b'):\n","          if b.text == 'Agenda':\n","            for p in b.find_all_next('p'):\n","              text.append(p.text)\n","      text_list.append(text)\n","counter = 0\n","for i in range(len(text_list)):\n","  if len(text_list[i]) == 0:\n","    print(document_name[i])\n","    counter += 1\n","\n","print(counter)"]},{"cell_type":"markdown","metadata":{"id":"_jXWoVbe32yO"},"source":["In the following code block we are breaking apart each meeting note's list of text and combining it into one large block of text. This way each meeting note has its own single block of text."]},{"cell_type":"code","execution_count":null,"metadata":{"id":"Jtlx7x36D57o"},"outputs":[],"source":["dictionaryOfNotes = {}\n","for doc, text in zip(document_name, text_list):\n","    text_clean = []\n","    for line in text:\n","      line = line.split(' ')\n","      tempList = []\n","      for word in line:\n","        if '=' not in word:\n","          tempList.append(word)\n","      line = ' '.join(tempList)\n","      text_clean.append(line)\n","    dictionaryOfNotes[doc] = \" \".join(text_clean)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"k-y7GjcxTu4b"},"outputs":[],"source":[" #print(te.get_emotion(' '.join(text_list[30])))\n","\n","# te.get_emotion(\"wow this package is really amazing\")\n","sentiment_dictionary = {}\n","for meeting, text in dictionaryOfNotes.items():\n","  sentiment_dictionary[meeting] = te.get_emotion(text)\n"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":337,"status":"ok","timestamp":1681241603632,"user":{"displayName":"Tim Poll","userId":"04586018797185094655"},"user_tz":300},"id":"euoAtg-KWhsL","outputId":"cf34c9ce-09c0-4afe-bd3b-9623969d2643"},"outputs":[{"data":{"text/plain":["610"]},"execution_count":18,"metadata":{},"output_type":"execute_result"}],"source":["sentiment_dictionary2 = {}\n","for key, val in sentiment_dictionary.items():\n","  summ = 0\n","  for score in val.values():\n","    summ += score\n","  if summ != 0:\n","    sentiment_dictionary2[key] = val\n","\n","len(sentiment_dictionary)"]},{"cell_type":"markdown","metadata":{"id":"0B1IjYUyCb8m"},"source":["Exporting data as a text file"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"background_save":true},"executionInfo":{"elapsed":340,"status":"ok","timestamp":1681182630065,"user":{"displayName":"Tim Poll","userId":"04586018797185094655"},"user_tz":300},"id":"gNfFqblM7aSF","outputId":"5bff464e-7eec-4314-db23-28043ee9d109"},"outputs":[{"name":"stderr","output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"name":"stdout","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-23-3bdf95ea183a>\", line 1, in <cell line: 1>\n","    os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.9/inspect.py\", line 1543, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.9/inspect.py\", line 1501, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.9/inspect.py\", line 709, in getsourcefile\n","    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n","  File \"/usr/lib/python3.9/inspect.py\", line 738, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.9/inspect.py\", line 722, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.9/posixpath.py\", line 380, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-23-3bdf95ea183a>\", line 1, in <cell line: 1>\n","    os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.9/inspect.py\", line 1543, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.9/inspect.py\", line 1501, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.9/inspect.py\", line 709, in getsourcefile\n","    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n","  File \"/usr/lib/python3.9/inspect.py\", line 738, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.9/inspect.py\", line 722, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.9/posixpath.py\", line 380, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-23-3bdf95ea183a>\", line 1, in <cell line: 1>\n","    os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.9/inspect.py\", line 1543, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.9/inspect.py\", line 1501, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.9/inspect.py\", line 709, in getsourcefile\n","    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n","  File \"/usr/lib/python3.9/inspect.py\", line 738, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.9/inspect.py\", line 722, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.9/posixpath.py\", line 380, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["os.getcwd()\n","with open('/content/drive/MyDrive/PracticumIIsentimentResults.txt','w') as fileHandle:\n","  json.dump(sentiment_dictionary2, fileHandle)"]},{"cell_type":"markdown","metadata":{"id":"C_tzNyDlCij3"},"source":["Writing code to put the data into a csv"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"FHC7YY6ZChOB"},"outputs":[],"source":["name = []\n","Happy = []\n","Angry = []\n","Surprise = []\n","Sad = []\n","Fear = [] \n","sentiments = ['Happy','Angry','Surprise','Sad','Fear']\n","for key, value in sentiment_dictionary2.items():\n","  name.append(key)\n","  for key2, value2 in value.items():\n","    for emotion in sentiments:\n","      if key2 == 'Happy':\n","         Happy.append(value2)\n","      elif key2 == 'Angry':\n","         Angry.append(value2)\n","      elif key2 == 'Surprise':\n","         Surprise.append(value2)\n","      elif key2 == 'Sad':\n","         Sad.append(value2)\n","      elif key2 == 'Fear':\n","         Fear.append(value2)\n","\n","data_for_export = pd.DataFrame(list(zip(name,Happy,Angry,Surprise,Sad,Fear)), columns = ['Meeting Name','Happy','Angry','Surprise','Sad','Fear'])"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"background_save":true,"base_uri":"https://localhost:8080/"},"id":"6cauqflFHME4","outputId":"6b6940c6-ee1c-41f9-ef3f-5a3fb59d3309"},"outputs":[{"name":"stderr","output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"name":"stdout","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-20-c4e035d1e814>\", line 2, in <cell line: 2>\n","    data_for_export.to_csv('/content/drive/MyDrive/PracticumIIsentimentResultsV2.csv')\n","  File \"/usr/local/lib/python3.9/dist-packages/pandas/core/generic.py\", line 3551, in to_csv\n","    return DataFrameRenderer(formatter).to_csv(\n","  File \"/usr/local/lib/python3.9/dist-packages/pandas/io/formats/format.py\", line 1180, in to_csv\n","    csv_formatter.save()\n","  File \"/usr/local/lib/python3.9/dist-packages/pandas/io/formats/csvs.py\", line 241, in save\n","    with get_handle(\n","  File \"/usr/local/lib/python3.9/dist-packages/pandas/io/common.py\", line 658, in get_handle\n","    if _is_binary_mode(path_or_buf, mode) and \"b\" not in mode:\n","  File \"/usr/local/lib/python3.9/dist-packages/pandas/io/common.py\", line 1125, in _is_binary_mode\n","    return isinstance(handle, _get_binary_io_classes()) or \"b\" in getattr(\n","  File \"/usr/local/lib/python3.9/dist-packages/pandas/io/common.py\", line 1140, in _get_binary_io_classes\n","    zstd = import_optional_dependency(\"zstandard\", errors=\"ignore\")\n","  File \"/usr/local/lib/python3.9/dist-packages/pandas/compat/_optional.py\", line 138, in import_optional_dependency\n","    module = importlib.import_module(name)\n","  File \"/usr/lib/python3.9/importlib/__init__.py\", line 127, in import_module\n","    return _bootstrap._gcd_import(name[level:], package, level)\n","  File \"<frozen importlib._bootstrap>\", line 1030, in _gcd_import\n","  File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\n","  File \"<frozen importlib._bootstrap>\", line 982, in _find_and_load_unlocked\n","  File \"<frozen importlib._bootstrap>\", line 925, in _find_spec\n","  File \"<frozen importlib._bootstrap_external>\", line 1423, in find_spec\n","  File \"<frozen importlib._bootstrap_external>\", line 1392, in _get_spec\n","  File \"<frozen importlib._bootstrap_external>\", line 1356, in _path_importer_cache\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.9/inspect.py\", line 1543, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.9/inspect.py\", line 1501, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.9/inspect.py\", line 709, in getsourcefile\n","    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n","  File \"/usr/lib/python3.9/inspect.py\", line 738, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.9/inspect.py\", line 722, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.9/posixpath.py\", line 380, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-20-c4e035d1e814>\", line 2, in <cell line: 2>\n","    data_for_export.to_csv('/content/drive/MyDrive/PracticumIIsentimentResultsV2.csv')\n","  File \"/usr/local/lib/python3.9/dist-packages/pandas/core/generic.py\", line 3551, in to_csv\n","    return DataFrameRenderer(formatter).to_csv(\n","  File \"/usr/local/lib/python3.9/dist-packages/pandas/io/formats/format.py\", line 1180, in to_csv\n","    csv_formatter.save()\n","  File \"/usr/local/lib/python3.9/dist-packages/pandas/io/formats/csvs.py\", line 241, in save\n","    with get_handle(\n","  File \"/usr/local/lib/python3.9/dist-packages/pandas/io/common.py\", line 658, in get_handle\n","    if _is_binary_mode(path_or_buf, mode) and \"b\" not in mode:\n","  File \"/usr/local/lib/python3.9/dist-packages/pandas/io/common.py\", line 1125, in _is_binary_mode\n","    return isinstance(handle, _get_binary_io_classes()) or \"b\" in getattr(\n","  File \"/usr/local/lib/python3.9/dist-packages/pandas/io/common.py\", line 1140, in _get_binary_io_classes\n","    zstd = import_optional_dependency(\"zstandard\", errors=\"ignore\")\n","  File \"/usr/local/lib/python3.9/dist-packages/pandas/compat/_optional.py\", line 138, in import_optional_dependency\n","    module = importlib.import_module(name)\n","  File \"/usr/lib/python3.9/importlib/__init__.py\", line 127, in import_module\n","    return _bootstrap._gcd_import(name[level:], package, level)\n","  File \"<frozen importlib._bootstrap>\", line 1030, in _gcd_import\n","  File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\n","  File \"<frozen importlib._bootstrap>\", line 982, in _find_and_load_unlocked\n","  File \"<frozen importlib._bootstrap>\", line 925, in _find_spec\n","  File \"<frozen importlib._bootstrap_external>\", line 1423, in find_spec\n","  File \"<frozen importlib._bootstrap_external>\", line 1392, in _get_spec\n","  File \"<frozen importlib._bootstrap_external>\", line 1356, in _path_importer_cache\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.9/inspect.py\", line 1543, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.9/inspect.py\", line 1501, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.9/inspect.py\", line 709, in getsourcefile\n","    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n","  File \"/usr/lib/python3.9/inspect.py\", line 738, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.9/inspect.py\", line 722, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.9/posixpath.py\", line 380, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-20-c4e035d1e814>\", line 2, in <cell line: 2>\n","    data_for_export.to_csv('/content/drive/MyDrive/PracticumIIsentimentResultsV2.csv')\n","  File \"/usr/local/lib/python3.9/dist-packages/pandas/core/generic.py\", line 3551, in to_csv\n","    return DataFrameRenderer(formatter).to_csv(\n","  File \"/usr/local/lib/python3.9/dist-packages/pandas/io/formats/format.py\", line 1180, in to_csv\n","    csv_formatter.save()\n","  File \"/usr/local/lib/python3.9/dist-packages/pandas/io/formats/csvs.py\", line 241, in save\n","    with get_handle(\n","  File \"/usr/local/lib/python3.9/dist-packages/pandas/io/common.py\", line 658, in get_handle\n","    if _is_binary_mode(path_or_buf, mode) and \"b\" not in mode:\n","  File \"/usr/local/lib/python3.9/dist-packages/pandas/io/common.py\", line 1125, in _is_binary_mode\n","    return isinstance(handle, _get_binary_io_classes()) or \"b\" in getattr(\n","  File \"/usr/local/lib/python3.9/dist-packages/pandas/io/common.py\", line 1140, in _get_binary_io_classes\n","    zstd = import_optional_dependency(\"zstandard\", errors=\"ignore\")\n","  File \"/usr/local/lib/python3.9/dist-packages/pandas/compat/_optional.py\", line 138, in import_optional_dependency\n","    module = importlib.import_module(name)\n","  File \"/usr/lib/python3.9/importlib/__init__.py\", line 127, in import_module\n","    return _bootstrap._gcd_import(name[level:], package, level)\n","  File \"<frozen importlib._bootstrap>\", line 1030, in _gcd_import\n","  File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\n","  File \"<frozen importlib._bootstrap>\", line 982, in _find_and_load_unlocked\n","  File \"<frozen importlib._bootstrap>\", line 925, in _find_spec\n","  File \"<frozen importlib._bootstrap_external>\", line 1423, in find_spec\n","  File \"<frozen importlib._bootstrap_external>\", line 1392, in _get_spec\n","  File \"<frozen importlib._bootstrap_external>\", line 1356, in _path_importer_cache\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.9/inspect.py\", line 1543, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.9/inspect.py\", line 1501, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.9/inspect.py\", line 709, in getsourcefile\n","    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n","  File \"/usr/lib/python3.9/inspect.py\", line 738, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.9/inspect.py\", line 722, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.9/posixpath.py\", line 380, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["data_for_export.head()\n","data_for_export.to_csv('/content/drive/MyDrive/PracticumIIsentimentResultsV2.csv')"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"9CIY9Q0Zxi8J"},"outputs":[],"source":["test = \"We took the temperature of Noisebridge. People felt things were stable and pretty good these days, but the communities was a bit scattered and didn't always know all the cool things that go on --- people don't use nb-discuss to share stuff any more. Suggestions: a big party, a new mailing list, noisebridge university (which Jesse and Jake are working on), actually use the blog, a primary reduction party. Kelly agrees to set up noisebridgefuckyeah.tumblr.com\""]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":763,"status":"ok","timestamp":1680654055785,"user":{"displayName":"Tim Poll","userId":"04586018797185094655"},"user_tz":300},"id":"yTGSZIo9wtyH","outputId":"d351f2e1-4848-4bca-8cc6-ccac59408908"},"outputs":[{"data":{"text/plain":["{'Happy': 0.27, 'Angry': 0.09, 'Surprise': 0.18, 'Sad': 0.18, 'Fear': 0.27}"]},"execution_count":7,"metadata":{},"output_type":"execute_result"}],"source":["te.get_emotion(test)"]}],"metadata":{"colab":{"provenance":[]},"gpuClass":"standard","kernelspec":{"display_name":"Python 3","name":"python3"},"language_info":{"name":"python"}},"nbformat":4,"nbformat_minor":0}